#!/usr/bin/env bash

# ENVORINMNENT VARIABLES
# ----------------------
# WALLHAVEN_API - API key from wallhaven.cc
# WALLHAVEN_USER - Username from wallhaven.cc

WALLHAVEN_API=XXMiYVopgEjJlslkFOWxkmbdM1k4nGEi
WALLHAVEN_USER=fatnic

CACHE_DIR="$HOME/.cache/wallhaven"
mkdir -p $CACHE_DIR

> $CACHE_DIR/images

for ((i=1; i<=3; i++)); do
RESULT=$(curl -s -H "Content-Type:application/json" "https://wallhaven.cc/api/v1/search?sorting=toplist&purity=111&ratios=landscape&topRange=1M&page=$i&apikey=$WALLHAVEN_API")
    echo "$RESULT" | jq -r '.data[].path ' >> $CACHE_DIR/images
done

SELECTED=$(cat $CACHE_DIR/images | shuf -n 1)

CACHED="$CACHE_DIR/$(basename $SELECTED)"

if [ ! -f $CACHED ]; then
  curl -o "$CACHED" "$SELECTED"
fi 

$HOME/.dotfiles/scripts/setwallpaper "$CACHED"
