#!/usr/bin/env bash

# ENVORINMNENT VARIABLES
# ----------------------
# WALLHAVEN_API - API key from wallhaven.cc
# WALLHAVEN_USER - Username from wallhaven.cc

WALLHAVEN_API=XXMiYVopgEjJlslkFOWxkmbdM1k4nGEi
WALLHAVEN_USER=fatnic

CACHE_DIR="$HOME/.cache/wallhaven"
mkdir -p $CACHE_DIR

COLLECTION_NAME=$(echo $1 | rev | cut -d"/" -f 1 | rev)

RESULT=$(curl -s -H "Content-Type:application/json" "https://wallhaven.cc/api/v1/collections?apikey=$WALLHAVEN_API")
COLLECTION_ID=$(echo "$RESULT" | jq --arg LABEL "$COLLECTION_NAME" '.data[] | select(.label == $LABEL) | .id')

RESULT=$(curl -s -H "Content-Type:application/json" "https://wallhaven.cc/api/v1/collections/$WALLHAVEN_USER/$COLLECTION_ID?apikey=$WALLHAVEN_API")
PAGES=$(echo "$RESULT" | jq '.meta.last_page')

> $CACHE_DIR/images

for ((i=1; i<=$PAGES; i++)); do
    RESULT=$(curl -s -H "Content-Type:application/json" "https://wallhaven.cc/api/v1/collections/fatnic/$COLLECTION_ID?page=$i&apikey=$WALLHAVEN_API")
    echo "$RESULT" | jq -r '.data[].path ' >> $CACHE_DIR/images
done

SELECTED=$(cat $CACHE_DIR/images | shuf -n 1)

CACHED="$CACHE_DIR/$(basename $SELECTED)"

if [ ! -f $CACHED ]; then
  curl -o "$CACHED" "$SELECTED"
fi 

$HOME/.dotfiles/scripts/setwallpaper "$CACHED"
