#!/usr/bin/env bash

if [ -n "$1" ]; then
  IMG=$1
else
  read IMG
  echo $IMG
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  swww img --transition-step=255 --transition-fps=255 $IMG
  wal -i $IMG
  nohup hyprctrl reload >/dev/null 2>&1 &
  nohup /home/dave/.dotfiles/waybar/launch.sh >/dev/null 2>&1 &
  nohup swaync-client -rs >/dev/null 2>&1 &
elif [[ "$OSTYPE" == "darwin" ]]; then
  echo "This be MAC"
fi
