#!/usr/bin/env bash

# ENVORINMNENT VARIABLES
# ----------------------
# WALLHAVEN_API - API key from wallhaven.cc
# WALLHAVEN_USER - Username from wallhaven.cc

source $HOME/.dotfiles/.env

CACHE_DIR="$HOME/.cache/wallhaven"
PAGES=5
CATEGORIES=111
PURITY=110

Help() 
{
  echo "Wallpaper switcher for wallhaven.cc"
  echo ""
  echo "Required env variables:"
  echo "WALLHAVEN_API - API key from wallhaven.cc"
  echo "WALLHAVEN_USER - wallhaven username"
  echo ""
  echo "Syntax: wallhaven [-options]"
  echo "options:"
  echo " -c   collection name"
  echo " -t   get random from toplist"
  echo " -x   filter naughty stuff in bits sfw|risky|nsfw (default : 110)"
  echo " -k   k... ategories general|anime|people (default: 111)"
  echo " -p   how many toplist pages to pick from [default : $PAGES]"
  echo " -r   random image with query"
  echo " -i   get wallpaper by wallhaven id"
  echo " -d   delete cache"
  echo " -h   help menu"
  echo ""
  echo "Dependancies: curl, jq"
}

GetCollection()
{
  RESULT=$(curl -s -H "Content-Type:application/json" "https://wallhaven.cc/api/v1/collections?apikey=$WALLHAVEN_API")
  COLLECTION_ID=$(echo "$RESULT" | jq --arg LABEL "$COLLECTION" '.data[] | select(.label == $LABEL) | .id')

  RESULT=$(curl -s -H "Content-Type:application/json" "https://wallhaven.cc/api/v1/collections/$WALLHAVEN_USER/$COLLECTION_ID?apikey=$WALLHAVEN_API")
  PAGES=$(echo "$RESULT" | jq '.meta.last_page')

  > $CACHE_DIR/images

  for ((i=1; i<=$PAGES; i++)); do
      RESULT=$(curl -s -H "Content-Type:application/json" "https://wallhaven.cc/api/v1/collections/fatnic/$COLLECTION_ID?page=$i&apikey=$WALLHAVEN_API")
      echo "$RESULT" | jq -r '.data[].path ' >> $CACHE_DIR/images
  done

  SELECTED=$(cat $CACHE_DIR/images | shuf -n 1)

  CACHED="$CACHE_DIR/$(basename $SELECTED)"

  if [ ! -f $CACHED ]; then
    curl -o "$CACHED" "$SELECTED"
  fi 

  echo "$CACHED"
}

GetToplist()
{
  > $CACHE_DIR/images
  SEED="$RANDOM"
  for ((i=1; i<=$PAGES; i++)); do
    RESULT=$(curl -s -H "Content-Type:application/json" \
        "https://wallhaven.cc/api/v1/search?sorting=toplist&categories=$CATEGORIES&purity=$PURITY&seed=$SEED&ratios=landscape&topRange=1M&page=$i&apikey=$WALLHAVEN_API")
        echo "$RESULT" | jq -r '.data[].path ' >> $CACHE_DIR/images
  done
  SELECTED=$(cat $CACHE_DIR/images | shuf -n 1)
  CACHED="$CACHE_DIR/$(basename $SELECTED)"
  if [ ! -f $CACHED ]; then
    curl -o "$CACHED" "$SELECTED"
  fi 
  echo "$CACHED"
}

GetRandom()
{
  > $CACHE_DIR/images
  SEED="$RANDOM"
    RESULT=$(curl -s -H "Content-Type:application/json" \
        "https://wallhaven.cc/api/v1/search?q=$QUERY&sorting=random&categories=$CATEGORIES&purity=$PURITY&seed=$SEED&ratios=landscape&&apikey=$WALLHAVEN_API")
        echo "$RESULT" | jq -r '.data[].path ' >> $CACHE_DIR/images
  SELECTED=$(cat $CACHE_DIR/images | shuf -n 1)
  CACHED="$CACHE_DIR/$(basename $SELECTED)"
  if [ ! -f $CACHED ]; then
    curl -o "$CACHED" "$SELECTED"
  fi 
  echo "$CACHED"
}

GetByID()
{
  > $CACHE_DIR/images
  RESULT=$(curl -s -H "Content-Type:application/json" "https://wallhaven.cc/api/v1/w/$WID?apikey=$WALLHAVEN_API")
  SELECTED=$(echo "$RESULT" | jq -r '.data.path')
  CACHED="$CACHE_DIR/$(basename $SELECTED)"
  if [ ! -f $CACHED ]; then
    curl -o "$CACHED" "$SELECTED"
  fi 
  echo "$CACHED"
}

DeleteCache()
{
  rm $CACHE_DIR/*
}

while getopts "hc:tr:p:dx:i:k:" option; do
  case $option in 
    h)
      Help
      exit;;
    c)
      COLLECTION=$OPTARG;;
    t)
      TOPLIST=X;;
    p)
      PAGES=$OPTARG;;
    r)
      QUERY=$OPTARG;;
    i)
      WID=$OPTARG;;
    x)
      PURITY=$OPTARG;;
    k)
      CATEGORIES=$OPTARG;;
    d)
      DeleteCache
      exit;;
    \?)
      echo "Invalid option"
      exit;;
  esac
done

mkdir -p $CACHE_DIR

if [[ -v WID ]]; then
  GetByID
  exit
fi

if [[ -v TOPLIST ]]; then
  GetToplist
  exit
fi

if [[ -v COLLECTION ]]; then
  GetCollection
  exit
fi

if [[ -v QUERY ]]; then
  GetRandom
  exit
fi
